### ISSUE TITLE
Can't locate dns.txt while use dnsenum in other dir

### ISSUE THREAD

**Issue by ignisc4t** [SparrowOchon/dnsenum2#6]
I made an `alias` for `dnsenum`, so I can use it wherever in current directory.
all works perfect  except the part :

```
Brute forcing with /storage/emulated/0/sampah/dns.txt:
_______________________________________________________

Error: make sure that the file /storage/emulated/0/sampah/dns.txt exists and has a size greater than zero.
```
any workaround to get this fixed ?

example :
`dnsenum` dir in `~/storage/emulated/0/sampah/dnsenum2/dnsenum.pl`
run `dnsenum` in `~/` will result something like above error.

running it on termux. thanks for update the death repo :)

**Comment by SparrowOchon** [comment]
To confirm, did you create a subdirectory in `~/` or alias it to `/` since the path to the folder `/storage/emulated/0/sampah/dnsenum2/dnsenum.pl` will not be under `~` by default in Android's directory tree.

Secondly, can you `cat` the Perl script, or does it give you a permission error in termux. This might be far fetched but rather make sure it's not a permissions issue right off the bat.

**Comment by ignisc4t** [comment]
> To confirm, did you create a subdirectory in `~/` or alias it to `/` since the path to the folder `/storage/emulated/0/sampah/dnsenum2/dnsenum.pl` will not be under `~` by default in Android's directory tree.
> 
> Secondly, can you `cat` the Perl script, or does it give you a permission error in termux. This might be far fetched but rather make sure it's not a permissions issue right off the bat.

Edit : pressed wrong button.
no worries, everything seem fine.
I just had to do it manually, edit the `Makefile` and change the destination to provide the full `PATH` in termux ;

```
        install -D -m 644 dns.txt -t $(DESTDIR)/data/data/com.termux/files/usr/share/dnsenum/
        install -D -m 644 dnsenum.1 -t $(DESTDIR)/data/data/com.termux/files/usr/share/man/man1/
        install -D -m 755 dnsenum.pl $(DESTDIR)/data/data/com.termux/files/usr/bin/dnsenum
```

for `dnsenum.pl` I change this line:
`my $default_dir = '/data/data/com.termux/files/usr/share/dnsenum/dns.txt';`

I'leave it that way because maybe will get some update in dns.txt in the future, so easy edit rather than `cd` into `/usr/share/dnsenum/`.

if I just make a change in `Makefile` alone leaving `dnsenum.pl` as it is, it'll return the same error. 

```
make
make install
```
here's the result:
```
[$]► which dnsenum
/data/data/com.termux/files/usr/bin/dnsenum
[$]► dnsenum
dnsenum.pl VERSION:1.2.6
Usage: dnsenum.pl [Options] <domain>
[Options]:
Note: If no -f tag supplied will default to /usr/share/dnsenum/dns.txt or
the dns.txt file in the same directory as dnsenum.pl
GENERAL OPTIONS:
  --dnsserver   <server>
                        Use this DNS server for A, NS and MX queries.
  --enum                Shortcut option equivalent to --threads 5 -s 15 -w.
  -h, --help            Print this help message.
  --noreverse           Skip the reverse lookup operations.
  --nocolor             Disable ANSIColor output.
  --private             Show and save private ips at the end of the file domain_ips.txt.
  --subfile <file>      Write all valid subdomains to this file.
  -t, --timeout <value> The tcp and udp timeout values in seconds (default: 10s).
  --threads <value>     The number of threads that will perform different queries.
  -v, --verbose         Be verbose: show all the progress and all the error messages.
GOOGLE SCRAPING OPTIONS:
  -p, --pages <value>   The number of google search pages to process when scraping names,
                        the default is 5 pages, the -s switch must be specified.
  -s, --scrap <value>   The maximum number of subdomains that will be scraped from Google (default 15).
BRUTE FORCE OPTIONS:
  -f, --file <file>     Read subdomains from this file to perform brute force. (Takes priority over default dns.txt)
  -u, --update  <a|g|r|z>
                        Update the file specified with the -f switch with valid subdomains.
        a (all)         Update using all results.
        g               Update using only google scraping results.
        r               Update using only reverse lookup results.
        z               Update using only zonetransfer results.
  -r, --recursion       Recursion on subdomains, brute force all discovred subdomains that have an NS record.
WHOIS NETRANGE OPTIONS:
  -d, --delay <value>   The maximum value of seconds to wait between whois queries, the value is defined randomly, default: 3s.
  -w, --whois           Perform the whois queries on c class network ranges.
                         **Warning**: this can generate very large netranges and it will take lot of time to performe reverse lookups.
REVERSE LOOKUP OPTIONS:
  -e, --exclude <regexp>
                        Exclude PTR records that match the regexp expression from reverse lookup results, useful on invalid hostnames.
OUTPUT OPTIONS:
  -o --output <file>    Output in XML format. Can be imported in MagicTree (www.gremwell.com)
[$]►
```

how about make it detect the environment ?

**Comment by SparrowOchon** [comment]
Keep in mind the Makefile will generate the directory structure it needs to execute by default. This means that independent of the platform, the default install will build a runnable script. 
 
If you want to change the directory structure, the easiest solution I can suggest is using the `-f` flag and specifying the `dns.txt` file as an alias. This way, you only need to edit the Makefile to determine the location to build the `dns.txt.` This will allow you to build it according to a custom structure specified in the Makefile ( which you can edit to where you want your files) and not have to touch the script itself.

**Comment by ignisc4t** [comment]
> Keep in mind the Makefile will generate the directory structure it needs to execute by default. This means that independent of the platform, the default install will build a runnable script.
> 
> If you want to change the directory structure, the easiest solution I can suggest is using the `-f` flag and specifying the `dns.txt` file as an alias. This way, you only need to edit the Makefile to determine the location to build the `dns.txt.` This will allow you to build it according to a custom structure specified in the Makefile ( which you can edit to where you want your files) and not have to touch the script itself.

yah, I can see that. been doing something like this for a while. make something working on termux is just awesome. as long as eveything is fine  no worries. the tool working, just google blocking queries. will keep this tool since installing dependencies itself is just really pain in the head (even with cpanm, the time it took, lol).

anyway, thanks for reviving the death repo tho, so we can enjoy this tool. 👍

**Comment by SparrowOchon** [comment]
No problem. Glad I could help.
